<div class="faq" data-mage-init='{"faq":{}}'>
    <h2><?= $block->escapeHtml(__('faq')) ?></h2>
    <h3 class="faq-title">title 1</h3>
    <div class="faq-content">
        <p>Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
    </div>
    <h3 class="faq-title">title 2</h3>
    <div class="faq-content">
        <p>At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio.</p>
    </div>
</div>
